### ISSUE TITLE
Hello, is the EMG data here three channels?

### ISSUE THREAD

**Issue by CUITCHENSIYU** [MikeMpapa/MLEmg_Monitoring_Physical_Fatigue#1]
Hello, is the EMG data here three channels?

**Comment by CUITCHENSIYU** [comment]
Can you briefly describe your data, especially the shape of the data, thank you

**Comment by MikeMpapa** [comment]
Hi, the data are available for download here: https://www.dropbox.com/s/daj4du1ra5zo821/Fatigue%20Data.zip?dl=0

**Comment by CUITCHENSIYU** [comment]
Thanks
