### ISSUE TITLE
Hello, here is a question. 

### ISSUE THREAD

**Issue by CUITCHENSIYU** [MikeMpapa/MLEmg_Monitoring_Physical_Fatigue#2]
Hello, here is a question. I visualized the data in the folder: "original_times_Study1" and found that it is a straight line. Why is it such a shape? I think EMG data should be a curve.

**Comment by MikeMpapa** [comment]
These are timestamps. Check this 'Study1_medfilt11_EMG' folder and the data in the link I shared with you.
